# 版本
version: "3.5"
# 服务
services:
        # 定义一个spider服务
        spider:
                # 用那个image开启服务
                image: "lymmurrain/90spider:12.0"
                # 数据卷，code在一级key的volumes中已定义
                volumes:
                        # 挂载卷用作调试及查看日志,注意卷里有源码，建议不要像我这样，我只是贪图方便。
                        - code:/root/comics90
                # 依赖于mongodb及redis服务，但启动顺序并不一定会先启动玩mongo和redis再启动spider
                depends_on:
                        - "mongodb"
                        - "redis"
                # deploy为stack部署的参数
                deploy:
                        # mode为 global，即每个节点部署一个该服务
                        mode: global
                # 所用网络,在一级key的networks中已定义,stack部署会自动创建一个overlay网络用作容器通信。除非网络已存在
                # 而docker-compose单机部署会自动创建一个bridge网络。除非网络已存在
                networks:
                        - "spider"
        mongodb:
                image: "mongo"
                # 挂载卷作持续存储
                volumes:
                        - mongodb:/data/db
                # 端口映射
                ports:
                        - "22222:27017"
                networks:
                        - "spider"
                deploy:
                        # 服务副本数为一，因为只需统一储存在一个服务器的mongo中。
                        replicas: 1
                        # 该服务该放在哪个节点的配置
                        placement:
                                         # 约束条件，放在manager节点上，由于只有一个manager节点，
                                         # 所以只在该manager节点上部署
                                         constraints: [node.role == manager]
                # 环境变量，设置root权限的username和密码
             	environment:
                             MONGO_INITDB_ROOT_USERNAME: yourusername
                             MONGO_INITDB_ROOT_PASSWORD: yourpwd
				# 运行该服务所用的命令
                command:
                        # 由于服务器性能较差，设置wiredTigerCacheSizeGB为0.3
                        --wiredTigerCacheSizeGB 0.3

        redis:
                image: "redis"
                ports:
                        - "21111:6379"
                networks:
                        - "spider"
               	# 部署redis服务的时候要执行的命令
                command: redis-server --requirepass yourpwd

                deploy:
                        replicas: 1
                        placement:
                                        constraints: [node.role == manager]
# 定义服务所需volumes
volumes:
        code:
        mongodb:
# 定义服务所需networks
networks:
        spider: