version: "3.5"
services:
        spider:
                image: "lymmurrain/90spider:12.0"
                volumes:
                        - code:/root/comics90
                depends_on:
                        - "mongodb"
                        - "redis"
                deploy:
                        mode: global
                networks:
                        - "spider"
        mongodb:
                image: "mongo"
                volumes:
                        - mongodb:/data/db
                ports:
                        - "22222:27017"
                networks:
                        - "spider"
                command: --wiredTigerCacheSizeGB 0.3
                environment:
                             MONGO_INITDB_ROOT_USERNAME: lymmurrain
                             MONGO_INITDB_ROOT_PASSWORD: lymmurrain
                deploy:
                        replicas: 1
                        placement:
                                         constraints: [node.role == manager]

        redis:
                image: "redis"
                ports:
                        - "21111:6379"
                networks:
                        - "spider"
                command: redis-server --requirepass lymmurrain
                deploy:
                        replicas: 1
                        placement:
                                        constraints: [node.role == manager]
volumes:
        code:
        mongodb:
networks:
        spider: